name: About Me
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install
        run: yarn install
      - name: Validate
        run: yarn validate
      - name: Build
        env:
          NODE_ENV: production
        run: yarn build
      - name: Commit & Publish
        run: |
          cd public
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . && git commit -m "Site Build"
          remote_repo="https://${GITHUB_ACTOR}:${{secrets.PROFILE_PUSH_ACCESS_TOKEN}}@github.com/chet20r/chet20r.github.io.git"
          git push "${remote_repo}" HEAD:master --force
