name: About Me
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install
        run: yarn install
      - name: Validate
        run: yarn validate
      - name: Build
        env:
          NODE_ENV: production
        run: yarn build
      - name: Deploy
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          cd public && git init
          git add . && git commit -m "Publish site"
          git remote add origin https://github.com/chet20r/chet20r.github.io.git
          git branch -M master
          git push -u origin master
